name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE: ${{ secrets.REGISTRY_SERVER }}/camelia-studio/kiss-shot_acerola-orion_heart-under-blade

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to registry
        run: buildah login --username camelia --password camelia ${{ secrets.REGISTRY_SERVER }}

      - name: Build image
        run: |
          buildah bud \
            --layers \
            --cache-from ${{ env.IMAGE }}:cache \
            --cache-to ${{ env.IMAGE }}:cache \
            -t ${{ env.IMAGE }}:${{ gitea.ref_name }} \
            -t ${{ env.IMAGE }}:latest \
            .

      - name: Push image
        run: |
          buildah push ${{ env.IMAGE }}:${{ gitea.ref_name }}
          buildah push ${{ env.IMAGE }}:latest
