name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE: ${{ secrets.REGISTRY_SERVER }}/camelia-studio/kiss-shot_acerola-orion_heart-under-blade

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: camelia
          password: camelia

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ gitea.ref_name }}
            ${{ env.IMAGE }}:latest
