package org.camelia.studio.kiss.shot.acerola.models;

public enum ModuleSetting {
    ANTI_RECENT_ENABLED,
    ANTI_RECENT_MAX_AGE_DAYS,
    ANTI_RECENT_ACTION,
    ANTI_RECENT_TIMEOUT_SECONDS,
    ANTI_MENTION_ENABLED,
    ANTI_MENTION_LIMIT,
    ANTI_MENTION_WINDOW_SECONDS,
    ANTI_MENTION_ACTION,
    ANTI_MENTION_TIMEOUT_SECONDS,
    ANTI_MENTION_DELETE_MESSAGE,
    SANCTION_ACTION,
    SANCTION_TIMEOUT_SECONDS,
    SANCTION_BAN_HISTORY_DAYS,
    SANCTION_DELETE_MESSAGE
}
