CREATE TABLE "users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "discordId" varchar(255) NOT NULL UNIQUE,
    "createdAt" timestamp(6) without time zone,
    "updatedAt" timestamp(6) without time zone
);

CREATE TABLE "avertos" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reason" varchar(255),
    "file" varchar(255),
    "createdAt" timestamp(6) without time zone,
    "updatedAt" timestamp(6) without time zone,
    "user_id" bigint,
    "moderator_id" bigint,
    CONSTRAINT "fk_avertos_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
    CONSTRAINT "fk_avertos_moderator" FOREIGN KEY ("moderator_id") REFERENCES "users" ("id")
);
