CREATE TABLE "discord_servers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "discord_id" varchar(20) NOT NULL UNIQUE,
    "lifecycle" varchar(16) NOT NULL,
    "joined_at" timestamp(6) with time zone NOT NULL,
    "left_at" timestamp(6) with time zone,
    "created_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ck_discord_servers_lifecycle" CHECK ("lifecycle" IN ('ACTIVE', 'LEFT'))
);

CREATE TABLE "server_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_id" bigint NOT NULL UNIQUE,
    "locale" varchar(10) NOT NULL DEFAULT 'fr',
    "log_channel_id" varchar(20),
    "created_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_server_settings_server" FOREIGN KEY ("server_id") REFERENCES "discord_servers" ("id") ON DELETE CASCADE
);

CREATE TABLE "server_modules" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_id" bigint NOT NULL,
    "module" varchar(32) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'DISABLED',
    "suspension_reason" varchar(255),
    "created_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_server_modules_server" FOREIGN KEY ("server_id") REFERENCES "discord_servers" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_server_modules_server_module" UNIQUE ("server_id", "module"),
    CONSTRAINT "ck_server_modules_status" CHECK ("status" IN ('DISABLED', 'ACTIVE', 'SUSPENDED')),
    CONSTRAINT "ck_server_modules_module" CHECK ("module" IN (
        'WARNINGS',
        'AUTO_ROLE',
        'MUSIC',
        'VOICE_RECORDING',
        'BOT_MESSAGES',
        'LINK_ENRICHMENT',
        'INTEGRATION_REMOVAL',
        'ANTI_RAID',
        'AUTO_SANCTION_CHANNEL',
        'AUTO_SANCTION_ROLE'
    ))
);

ALTER TABLE "users"
    ALTER COLUMN "createdAt" TYPE timestamp(6) with time zone USING "createdAt" AT TIME ZONE 'UTC',
    ALTER COLUMN "updatedAt" TYPE timestamp(6) with time zone USING "updatedAt" AT TIME ZONE 'UTC';

ALTER TABLE "avertos"
    ALTER COLUMN "createdAt" TYPE timestamp(6) with time zone USING "createdAt" AT TIME ZONE 'UTC',
    ALTER COLUMN "updatedAt" TYPE timestamp(6) with time zone USING "updatedAt" AT TIME ZONE 'UTC',
    ADD COLUMN "server_id" bigint;

DO $migration$
DECLARE
    legacy_guild_id varchar(20) := NULLIF('${legacyGuildId}', '');
    legacy_server_id bigint;
BEGIN
    IF EXISTS (SELECT 1 FROM "avertos") AND legacy_guild_id IS NULL THEN
        RAISE EXCEPTION 'GUILD_ID is required once to migrate existing warnings';
    END IF;

    IF legacy_guild_id IS NOT NULL THEN
        INSERT INTO "discord_servers" ("discord_id", "lifecycle", "joined_at")
        VALUES (legacy_guild_id, 'ACTIVE', CURRENT_TIMESTAMP)
        ON CONFLICT ("discord_id") DO UPDATE
        SET "lifecycle" = 'ACTIVE', "left_at" = NULL, "updated_at" = CURRENT_TIMESTAMP
        RETURNING "id" INTO legacy_server_id;

        INSERT INTO "server_settings" ("server_id", "locale", "log_channel_id")
        VALUES (legacy_server_id, 'fr', NULLIF('${legacyLogChannelId}', ''))
        ON CONFLICT ("server_id") DO NOTHING;

        INSERT INTO "server_modules" ("server_id", "module", "status")
        SELECT legacy_server_id, module_name, 'DISABLED'
        FROM unnest(ARRAY[
            'WARNINGS',
            'AUTO_ROLE',
            'MUSIC',
            'VOICE_RECORDING',
            'BOT_MESSAGES',
            'LINK_ENRICHMENT',
            'INTEGRATION_REMOVAL',
            'ANTI_RAID',
            'AUTO_SANCTION_CHANNEL',
            'AUTO_SANCTION_ROLE'
        ]) AS module_name
        ON CONFLICT ("server_id", "module") DO NOTHING;

        UPDATE "avertos" SET "server_id" = legacy_server_id WHERE "server_id" IS NULL;
    END IF;
END
$migration$;

ALTER TABLE "avertos"
    ALTER COLUMN "server_id" SET NOT NULL,
    ADD CONSTRAINT "fk_avertos_server" FOREIGN KEY ("server_id") REFERENCES "discord_servers" ("id") ON DELETE CASCADE;

CREATE INDEX "idx_avertos_server_created_at" ON "avertos" ("server_id", "createdAt" DESC);
CREATE INDEX "idx_avertos_server_user" ON "avertos" ("server_id", "user_id");
