CREATE TABLE "server_module_roles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_module_id" bigint NOT NULL,
    "purpose" varchar(16) NOT NULL,
    "role_id" varchar(20) NOT NULL,
    CONSTRAINT "fk_server_module_roles_module" FOREIGN KEY ("server_module_id") REFERENCES "server_modules" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_server_module_roles_resource" UNIQUE ("server_module_id", "purpose", "role_id"),
    CONSTRAINT "ck_server_module_roles_purpose" CHECK ("purpose" IN ('TARGET', 'WATCHED', 'PROTECTED', 'EXCLUDED'))
);

CREATE TABLE "server_module_channels" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_module_id" bigint NOT NULL,
    "purpose" varchar(16) NOT NULL,
    "channel_id" varchar(20) NOT NULL,
    CONSTRAINT "fk_server_module_channels_module" FOREIGN KEY ("server_module_id") REFERENCES "server_modules" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_server_module_channels_resource" UNIQUE ("server_module_id", "purpose", "channel_id"),
    CONSTRAINT "ck_server_module_channels_purpose" CHECK ("purpose" IN ('TARGET', 'WATCHED', 'PROTECTED', 'EXCLUDED'))
);

CREATE TABLE "configuration_history" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_id" bigint NOT NULL,
    "actor_id" varchar(32) NOT NULL,
    "module" varchar(32),
    "setting" varchar(64) NOT NULL,
    "old_value" text,
    "new_value" text,
    "created_at" timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_configuration_history_server" FOREIGN KEY ("server_id") REFERENCES "discord_servers" ("id") ON DELETE CASCADE
);

CREATE INDEX "idx_configuration_history_server_created_at"
    ON "configuration_history" ("server_id", "created_at" DESC);

DO $migration$
DECLARE
    legacy_guild_id varchar(20) := NULLIF('${legacyGuildId}', '');
    legacy_server_id bigint;
    legacy_module_id bigint;
    resource_id varchar(20);
BEGIN
    IF legacy_guild_id IS NULL THEN
        IF NULLIF('${legacyLogChannelId}', '') IS NOT NULL
            OR NULLIF('${legacyDefaultRoleId}', '') IS NOT NULL
            OR NULLIF('${legacyAutoBanChannelIds}', '') IS NOT NULL
            OR NULLIF('${legacyAutoBanRoleIds}', '') IS NOT NULL
            OR NULLIF('${legacyProtectedRoleIds}', '') IS NOT NULL
            OR NULLIF('${legacyNoEmbedChannelIds}', '') IS NOT NULL THEN
            RAISE EXCEPTION 'GUILD_ID is required once to migrate existing module configuration';
        END IF;
        RETURN;
    END IF;

    INSERT INTO "discord_servers" ("discord_id", "lifecycle", "joined_at")
    VALUES (legacy_guild_id, 'ACTIVE', CURRENT_TIMESTAMP)
    ON CONFLICT ("discord_id") DO NOTHING;

    SELECT "id" INTO legacy_server_id
    FROM "discord_servers"
    WHERE "discord_id" = legacy_guild_id;

    INSERT INTO "server_settings" ("server_id", "locale", "log_channel_id")
    VALUES (legacy_server_id, 'fr', NULLIF('${legacyLogChannelId}', ''))
    ON CONFLICT ("server_id") DO UPDATE
    SET "log_channel_id" = COALESCE("server_settings"."log_channel_id", EXCLUDED."log_channel_id");

    INSERT INTO "server_modules" ("server_id", "module", "status")
    SELECT legacy_server_id, module_name, 'DISABLED'
    FROM unnest(ARRAY[
        'WARNINGS',
        'AUTO_ROLE',
        'MUSIC',
        'VOICE_RECORDING',
        'BOT_MESSAGES',
        'LINK_ENRICHMENT',
        'INTEGRATION_REMOVAL',
        'ANTI_RAID',
        'AUTO_SANCTION_CHANNEL',
        'AUTO_SANCTION_ROLE'
    ]) AS module_name
    ON CONFLICT ("server_id", "module") DO NOTHING;

    IF NULLIF('${legacyDefaultRoleId}', '') IS NOT NULL THEN
        SELECT "id" INTO legacy_module_id FROM "server_modules"
        WHERE "server_id" = legacy_server_id AND "module" = 'AUTO_ROLE';

        INSERT INTO "server_module_roles" ("server_module_id", "purpose", "role_id")
        VALUES (legacy_module_id, 'TARGET', '${legacyDefaultRoleId}')
        ON CONFLICT DO NOTHING;
    END IF;

    SELECT "id" INTO legacy_module_id FROM "server_modules"
    WHERE "server_id" = legacy_server_id AND "module" = 'AUTO_SANCTION_CHANNEL';
    FOR resource_id IN SELECT trim(value) FROM regexp_split_to_table('${legacyAutoBanChannelIds}', ',') value WHERE trim(value) <> '' LOOP
        INSERT INTO "server_module_channels" ("server_module_id", "purpose", "channel_id")
        VALUES (legacy_module_id, 'WATCHED', resource_id)
        ON CONFLICT DO NOTHING;
    END LOOP;

    SELECT "id" INTO legacy_module_id FROM "server_modules"
    WHERE "server_id" = legacy_server_id AND "module" = 'AUTO_SANCTION_ROLE';
    FOR resource_id IN SELECT trim(value) FROM regexp_split_to_table('${legacyAutoBanRoleIds}', ',') value WHERE trim(value) <> '' LOOP
        INSERT INTO "server_module_roles" ("server_module_id", "purpose", "role_id")
        VALUES (legacy_module_id, 'WATCHED', resource_id)
        ON CONFLICT DO NOTHING;
    END LOOP;

    FOR legacy_module_id IN
        SELECT "id" FROM "server_modules"
        WHERE "server_id" = legacy_server_id
          AND "module" IN ('ANTI_RAID', 'AUTO_SANCTION_CHANNEL', 'AUTO_SANCTION_ROLE')
    LOOP
        FOR resource_id IN SELECT trim(value) FROM regexp_split_to_table('${legacyProtectedRoleIds}', ',') value WHERE trim(value) <> '' LOOP
            INSERT INTO "server_module_roles" ("server_module_id", "purpose", "role_id")
            VALUES (legacy_module_id, 'PROTECTED', resource_id)
            ON CONFLICT DO NOTHING;
        END LOOP;
    END LOOP;

    SELECT "id" INTO legacy_module_id FROM "server_modules"
    WHERE "server_id" = legacy_server_id AND "module" = 'INTEGRATION_REMOVAL';
    FOR resource_id IN SELECT trim(value) FROM regexp_split_to_table('${legacyNoEmbedChannelIds}', ',') value WHERE trim(value) <> '' LOOP
        INSERT INTO "server_module_channels" ("server_module_id", "purpose", "channel_id")
        VALUES (legacy_module_id, 'WATCHED', resource_id)
        ON CONFLICT DO NOTHING;
    END LOOP;

    INSERT INTO "configuration_history" ("server_id", "actor_id", "setting", "new_value")
    VALUES (legacy_server_id, 'SYSTEM_MIGRATION', 'legacy_module_resources', 'imported');
END
$migration$;
