CREATE TABLE "server_module_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_module_id" bigint NOT NULL,
    "setting" varchar(64) NOT NULL,
    "value" text NOT NULL,
    CONSTRAINT "fk_server_module_settings_module" FOREIGN KEY ("server_module_id") REFERENCES "server_modules" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_server_module_settings_key" UNIQUE ("server_module_id", "setting")
);

CREATE TABLE "server_protected_roles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "server_id" bigint NOT NULL,
    "role_id" varchar(20) NOT NULL,
    CONSTRAINT "fk_server_protected_roles_server" FOREIGN KEY ("server_id") REFERENCES "discord_servers" ("id") ON DELETE CASCADE,
    CONSTRAINT "uk_server_protected_roles_resource" UNIQUE ("server_id", "role_id")
);

INSERT INTO "server_protected_roles" ("server_id", "role_id")
SELECT DISTINCT module."server_id", resource."role_id"
FROM "server_module_roles" resource
JOIN "server_modules" module ON module."id" = resource."server_module_id"
WHERE resource."purpose" = 'PROTECTED'
ON CONFLICT DO NOTHING;

DELETE FROM "server_module_roles" WHERE "purpose" = 'PROTECTED';

INSERT INTO "server_module_settings" ("server_module_id", "setting", "value")
SELECT module."id", setting."name", setting."value"
FROM "server_modules" module
CROSS JOIN (VALUES
    ('ANTI_RECENT_ENABLED', 'true'),
    ('ANTI_RECENT_MAX_AGE_DAYS', '7'),
    ('ANTI_RECENT_ACTION', 'KICK'),
    ('ANTI_RECENT_TIMEOUT_SECONDS', '600'),
    ('ANTI_MENTION_ENABLED', 'true'),
    ('ANTI_MENTION_LIMIT', '5'),
    ('ANTI_MENTION_WINDOW_SECONDS', '10'),
    ('ANTI_MENTION_ACTION', 'TIMEOUT'),
    ('ANTI_MENTION_TIMEOUT_SECONDS', '600'),
    ('ANTI_MENTION_DELETE_MESSAGE', 'false')
) AS setting("name", "value")
WHERE module."module" = 'ANTI_RAID'
ON CONFLICT DO NOTHING;

INSERT INTO "server_module_settings" ("server_module_id", "setting", "value")
SELECT module."id", setting."name", setting."value"
FROM "server_modules" module
CROSS JOIN (VALUES
    ('SANCTION_TIMEOUT_SECONDS', '600'),
    ('SANCTION_BAN_HISTORY_DAYS', '0'),
    ('SANCTION_DELETE_MESSAGE', 'false')
) AS setting("name", "value")
WHERE module."module" IN ('AUTO_SANCTION_CHANNEL', 'AUTO_SANCTION_ROLE')
ON CONFLICT DO NOTHING;

DO $migration$
DECLARE
    legacy_guild_id varchar(20) := NULLIF('${legacyGuildId}', '');
BEGIN
    IF legacy_guild_id IS NULL THEN
        RETURN;
    END IF;

    UPDATE "server_module_settings" setting
    SET "value" = CASE setting."setting"
        WHEN 'ANTI_RECENT_MAX_AGE_DAYS' THEN '${legacyAntiRaidMinimumAccountAgeDays}'
        WHEN 'ANTI_MENTION_LIMIT' THEN '${legacyAntiRaidMentionLimit}'
        WHEN 'ANTI_MENTION_WINDOW_SECONDS' THEN '${legacyAntiRaidMentionWindowSeconds}'
        ELSE setting."value"
    END
    FROM "server_modules" module
    JOIN "discord_servers" server ON server."id" = module."server_id"
    WHERE setting."server_module_id" = module."id"
      AND module."module" = 'ANTI_RAID'
      AND server."discord_id" = legacy_guild_id
      AND setting."setting" IN (
          'ANTI_RECENT_MAX_AGE_DAYS',
          'ANTI_MENTION_LIMIT',
          'ANTI_MENTION_WINDOW_SECONDS'
      );

    INSERT INTO "configuration_history" ("server_id", "actor_id", "module", "setting", "new_value")
    SELECT server."id", 'SYSTEM_MIGRATION', 'ANTI_RAID', 'legacy_anti_raid_settings', 'imported'
    FROM "discord_servers" server
    WHERE server."discord_id" = legacy_guild_id;
END
$migration$;
